steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lunchandlearn-224013/github.com/rohgoyal/nodeapp:$COMMIT_SHA', '.']
images: ['gcr.io/lunchandlearn-224013/github.com/rohgoyal/nodeapp:$COMMIT_SHA']
